[2023-12-19 01:52:06] [INFO    ] discord.client: logging in using static token
[2023-12-19 01:52:07] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7d56ed3b7f0054d8eabb3b120b9fe71a).
[2023-12-19 01:52:21] [ERROR   ] discord.ui.view: Ignoring exception in view <View timeout=180.0 children=3> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Read Here' emoji=None row=None>
Traceback (most recent call last):
  File "C:\Users\lyfes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\lyfes\Documents\Coding\MangaArc\cogs\manga.py", line 138, in hello_call
    await view.send(interaction.channel)
  File "c:\Users\lyfes\Documents\Coding\MangaArc\cogs\manga.py", line 13, in send
    await self.update_message(self.items[self.current_page - 1])
  File "c:\Users\lyfes\Documents\Coding\MangaArc\cogs\manga.py", line 24, in update_message
    await self.message.edit(embed=self.create_embed(data), view=self)
  File "C:\Users\lyfes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\message.py", line 2275, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lyfes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.image.url: Not a well formed URL.
[2023-12-19 01:52:24] [ERROR   ] discord.ui.view: Ignoring exception in view <PaginationView timeout=180.0 children=4> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=True label='Next' emoji=None row=None>
Traceback (most recent call last):
  File "C:\Users\lyfes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\lyfes\Documents\Coding\MangaArc\cogs\manga.py", line 65, in next_button
    await self.update_message(self.items[self.current_page - 1])
                              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
[2023-12-19 01:52:26] [ERROR   ] discord.ui.view: Ignoring exception in view <PaginationView timeout=180.0 children=4> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=True label='Previous' emoji=None row=None>
Traceback (most recent call last):
  File "C:\Users\lyfes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\lyfes\Documents\Coding\MangaArc\cogs\manga.py", line 59, in prev_button
    await self.update_message(self.items[self.current_page - 1])
  File "c:\Users\lyfes\Documents\Coding\MangaArc\cogs\manga.py", line 24, in update_message
    await self.message.edit(embed=self.create_embed(data), view=self)
  File "C:\Users\lyfes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\message.py", line 2275, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lyfes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.image.url: Not a well formed URL.
